# This is a basic workflow to help you get started with Actions

name: Automated build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore ChummerGenSR4.sln
        
      - name: Build the solution
        run: msbuild ChummerGenSR4.sln /p:Configuration=Release
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "ChummerGenSR4.zip"
          path: "bin"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "ChummerGenSR4.zip"
          path: "ChummerGenSR4.zip"
